const detailDefaults={
  ticket:220,salesDay:4.65,salesDayLow:4.3,salesDayHigh:5,daysWeek:5,completionRate:100,d2dRaiseSalesThreshold:4.3,
  founderWeeks:4.57,founderD2DDays:3,founderDetailDays:3,founderPartnerPay:18,founderHoursDay:9,founderDetailsDay:3,
  detailerPay:17,detailerRaise:1,detailerRaiseMonths:6,managerPay:22,managerRaise:1,managerRaiseMonths:6,
  adminPay:24,adminRaise:0,adminRaiseMonths:12,recruiterPay:24,recruitersPerOffice:0.5,
  d2dBase:300,d2dCommission:10,d2dRaise:1,d2dRaiseMonths:3,d2dCap:15,hoursWeek:40,weeksYear:52,
  vanPurchase:3000,vanSetup:2000,vanMonthly:1200,ipadPurchase:500,ipadService:40,hotspot:50,
  payrollTax:7.65,workersComp:2,paymentProcessing:3,recruitCost:150,
  officeSmall:1000,officeMedium:2200,officeLarge:3500,officeSetup:3500,otherOverhead:1500,
  post2030DetailerGrowth:20,post2030OfficeEveryDetailers:16
};

const capitalDefaults={startingBusinessCash:35000,ownerDistributionPct:15,personalTaxReservePct:30,annualPersonalSpend:48000,acquisitionReservePct:60};

const ventureDefaults={
  clothing:{name:'Clothing Brand',division:'Retail',startYear:2028,firstRevenue:300000,margin:15,sameStoreGrowth:14,employees:4,employeesPerLocation:5,reinvestPct:35,maxLocationGrowthPct:60,maxLocations:85,startupEquity:30000,expansionEquity:90000,totalProjectCost:30000,locationsPerCity:1,locationsPerState:5,marketPath:'Online nationwide → Raleigh/Charlotte pop-ups → Southeast flagships → major U.S. metros',note:'Online first. Add physical retail only after profitable online demand, repeat purchase and inventory turns support it.'},
  cleaning:{name:'Commercial Cleaning',division:'Service',startYear:2029,firstRevenue:500000,margin:18,sameStoreGrowth:10,employees:12,employeesPerLocation:14,reinvestPct:45,maxLocationGrowthPct:70,maxLocations:220,startupEquity:50000,expansionEquity:75000,totalProjectCost:50000,locationsPerCity:1,locationsPerState:7,marketPath:'Triangle → NC metros → Southeast → East Coast → national B2B hubs',note:'Recurring medical, office, retail and warehouse contracts. New branches open only after existing branches are profitable.'},
  pressure:{name:'Pressure Washing',division:'Service',startYear:2030,firstRevenue:350000,margin:22,sameStoreGrowth:11,employees:6,employeesPerLocation:8,reinvestPct:45,maxLocationGrowthPct:75,maxLocations:240,startupEquity:40000,expansionEquity:60000,totalProjectCost:40000,locationsPerCity:1,locationsPerState:8,marketPath:'Triangle → NC → Southeast → Sun Belt metros → national commercial routes',note:'Cross-sell detailing, HOA and property accounts. Expand from shared service hubs where possible.'},
  bowling:{name:'Bowling & Entertainment',division:'Entertainment',startYear:2032,firstRevenue:1800000,margin:16,sameStoreGrowth:6,employees:32,employeesPerLocation:38,reinvestPct:25,maxLocationGrowthPct:35,maxLocations:40,startupEquity:350000,expansionEquity:650000,totalProjectCost:2000000,locationsPerCity:1,locationsPerState:3,marketPath:'Raleigh acquisition → Charlotte/Greensboro → Southeast family-entertainment markets → selective national',note:'Acquire cash-flowing centers, renovate gradually, then duplicate only proven entertainment economics.'},
  commercialRE:{name:'Commercial Real Estate',division:'Real Estate',startYear:2032,firstRevenue:450000,margin:55,sameStoreGrowth:5,employees:3,employeesPerLocation:2,reinvestPct:35,maxLocationGrowthPct:40,maxLocations:150,startupEquity:450000,expansionEquity:500000,totalProjectCost:2500000,locationsPerCity:2,locationsPerState:10,marketPath:'Own operating buildings first → NC income properties → Southeast portfolio → diversified U.S. holdings',note:'Prioritize owner-occupied buildings and income assets with durable tenants and conservative leverage.'},
  constructionMgmt:{name:'Construction Management',division:'Construction',startYear:2033,firstRevenue:1200000,margin:12,sameStoreGrowth:10,employees:10,employeesPerLocation:12,reinvestPct:30,maxLocationGrowthPct:45,maxLocations:55,startupEquity:150000,expansionEquity:200000,totalProjectCost:250000,locationsPerCity:1,locationsPerState:4,marketPath:'NC projects → Southeast regional offices → markets where M Holdings develops assets',note:'Manage internal projects first, then selectively take external work to deepen expertise and buying power.'},
  apartmentDev:{name:'Apartment Development',division:'Real Estate',startYear:2034,firstRevenue:2500000,margin:18,sameStoreGrowth:8,employees:10,employeesPerLocation:8,reinvestPct:30,maxLocationGrowthPct:35,maxLocations:35,startupEquity:1500000,expansionEquity:2500000,totalProjectCost:120000000,locationsPerCity:1,locationsPerState:3,marketPath:'First NC community → Carolinas → Southeast growth metros → selective national developments',note:'Treat each location as an active development platform/project. Outside equity and construction debt fund most project cost.'},
  propertyMgmt:{name:'Property Management',division:'Real Estate',startYear:2035,firstRevenue:650000,margin:20,sameStoreGrowth:10,employees:12,employeesPerLocation:14,reinvestPct:40,maxLocationGrowthPct:60,maxLocations:140,startupEquity:100000,expansionEquity:120000,totalProjectCost:150000,locationsPerCity:1,locationsPerState:7,marketPath:'Manage M Holdings assets → third-party NC → Southeast → multi-state portfolio',note:'Build around owned properties, then add third-party units only where local density supports efficient teams.'},
  apartmentPortfolio:{name:'Apartment Ownership',division:'Real Estate',startYear:2036,firstRevenue:7500000,margin:48,sameStoreGrowth:5,employees:14,employeesPerLocation:7,reinvestPct:28,maxLocationGrowthPct:30,maxLocations:70,startupEquity:6000000,expansionEquity:4500000,totalProjectCost:120000000,locationsPerCity:1,locationsPerState:4,marketPath:'First stabilized luxury community → Carolinas → Southeast portfolio → diversified multifamily markets',note:'Locations represent stabilized communities. Expansion is intentionally slower because every asset requires substantial equity.'},
  generalContracting:{name:'General Contracting',division:'Construction',startYear:2036,firstRevenue:4500000,margin:9,sameStoreGrowth:10,employees:28,employeesPerLocation:30,reinvestPct:25,maxLocationGrowthPct:45,maxLocations:70,startupEquity:500000,expansionEquity:450000,totalProjectCost:1000000,locationsPerCity:1,locationsPerState:4,marketPath:'NC → Southeast offices aligned with development pipeline → selective external commercial work',note:'Use regional offices to serve internal development first; outside work fills capacity without distracting from core projects.'},
  hospitality:{name:'Hospitality & Resorts',division:'Hospitality',startYear:2038,firstRevenue:6000000,margin:20,sameStoreGrowth:7,employees:70,employeesPerLocation:85,reinvestPct:22,maxLocationGrowthPct:30,maxLocations:22,startupEquity:4000000,expansionEquity:6000000,totalProjectCost:25000000,locationsPerCity:1,locationsPerState:2,marketPath:'Boutique NC/Southeast property → destination resorts → coastal/tourism markets → island operating expertise',note:'Scale slowly. Every new property must prove guest satisfaction, stabilized occupancy and management depth.'},
  investment:{name:'Investment Company',division:'Capital',startYear:2039,firstRevenue:1200000,margin:35,sameStoreGrowth:15,employees:8,employeesPerLocation:10,reinvestPct:20,maxLocationGrowthPct:25,maxLocations:12,startupEquity:750000,expansionEquity:400000,totalProjectCost:1000000,locationsPerCity:1,locationsPerState:2,marketPath:'Central capital team → Southeast investor network → national institutional relationships',note:'Remain centralized longer than operating companies; add offices only when deal flow and investor relationships justify them.'},
  siteDev:{name:'Site Development',division:'Construction',startYear:2039,firstRevenue:5000000,margin:10,sameStoreGrowth:10,employees:35,employeesPerLocation:40,reinvestPct:25,maxLocationGrowthPct:40,maxLocations:55,startupEquity:1200000,expansionEquity:900000,totalProjectCost:3000000,locationsPerCity:1,locationsPerState:4,marketPath:'Internal NC projects → Southeast regional crews → external infrastructure/site contracts',note:'Heavy-equipment branches follow development density; do not scatter equipment across thin markets.'},
  island:{name:'Island Development',division:'Island',startYear:2045,firstRevenue:0,margin:0,sameStoreGrowth:0,employees:10,employeesPerLocation:120,reinvestPct:0,maxLocationGrowthPct:0,maxLocations:1,startupEquity:1500000,expansionEquity:0,totalProjectCost:150000000,locationsPerCity:1,locationsPerState:1,marketPath:'2045 feasibility → 2046 financing/logistics → 2047 acquisition + infrastructure',note:'2045 feasibility → 2046 financing/logistics → 2047 acquisition and infrastructure launch.',isIsland:true,island2047Equity:15000000}
};

const detailGroups=[
  {title:'Sales & service',subtitle:'The numbers that drive detailing revenue',keys:['ticket','salesDay','salesDayLow','salesDayHigh','daysWeek','completionRate']},
  {title:'Founder phase',subtitle:'Feb. 28–Mar. 31 before full-time launch',keys:['founderWeeks','founderD2DDays','founderDetailDays','founderPartnerPay','founderHoursDay','founderDetailsDay']},
  {title:'Pay & raises',subtitle:'Starting pay and automatic tenure raises',keys:['detailerPay','detailerRaise','detailerRaiseMonths','managerPay','managerRaise','managerRaiseMonths','adminPay','d2dBase','d2dCommission','d2dRaise','d2dRaiseMonths','d2dCap','d2dRaiseSalesThreshold']},
  {title:'Growth costs',subtitle:'Vans, iPads, recruiting and offices',keys:['vanPurchase','vanSetup','vanMonthly','ipadPurchase','ipadService','hotspot','recruitCost','officeSmall','officeMedium','officeLarge','officeSetup']},
  {title:'Long-range detailing',subtitle:'Controls annual scaling after 2030',keys:['post2030DetailerGrowth','post2030OfficeEveryDetailers']},
  {title:'Advanced overhead',subtitle:'Taxes, insurance, processing and recruiting support',keys:['hoursWeek','weeksYear','recruiterPay','recruitersPerOffice','payrollTax','workersComp','paymentProcessing','otherOverhead'],advanced:true}
];
const labels={ticket:'Average detail ($)',salesDay:'Planning avg details / day',salesDayLow:'Low target details / day',salesDayHigh:'High target details / day',daysWeek:'Selling days / week',completionRate:'Completed jobs %',d2dRaiseSalesThreshold:'D2D sales/day required for raises',founderWeeks:'Founder phase length (weeks)',founderD2DDays:'Your D2D days / week',founderDetailDays:'Partner detail days / week',founderPartnerPay:'Partner pay ($/hr)',founderHoursDay:'Partner hours / workday',founderDetailsDay:'Partner completed details / day',detailerPay:'Detailer starting $/hr',detailerRaise:'Detailer raise ($)',detailerRaiseMonths:'Detailer raise every (months)',managerPay:'Manager starting $/hr',managerRaise:'Manager raise ($)',managerRaiseMonths:'Manager raise every (months)',adminPay:'Admin starting $/hr',recruiterPay:'Recruiter $/hr',recruitersPerOffice:'Recruiters per office',d2dBase:'D2D base $/week',d2dCommission:'D2D starting commission %',d2dRaise:'D2D raise (points)',d2dRaiseMonths:'D2D raise every (months)',d2dCap:'D2D commission cap %',hoursWeek:'Hourly staff hours / week',weeksYear:'Weeks / year',vanPurchase:'Average van purchase ($)',vanSetup:'Van equipment/setup ($)',vanMonthly:'Van monthly operating ($)',ipadPurchase:'iPad purchase ($)',ipadService:'iPad service / month ($)',hotspot:'Hotspot / van / month ($)',payrollTax:'Employer payroll tax %',workersComp:'Workers comp / payroll %',paymentProcessing:'Card processing % of sales',recruitCost:'Recruiting / new hire ($)',officeSmall:'Small office / month ($)',officeMedium:'Medium office / month ($)',officeLarge:'Large office / month ($)',officeSetup:'New office setup ($)',otherOverhead:'Other overhead / month ($)',post2030DetailerGrowth:'Detailers annual growth after 2030 (%)',post2030OfficeEveryDetailers:'Add office per detailers after 2030'};

let detail={...detailDefaults,...JSON.parse(localStorage.getItem('mhDetail')||'{}')};
if(localStorage.getItem('mhModelVersion')!=='6'){detail.post2030DetailerGrowth=Math.max(20,+detail.post2030DetailerGrowth||0);detail.post2030OfficeEveryDetailers=Math.min(16,+detail.post2030OfficeEveryDetailers||16);localStorage.setItem('mhDetail',JSON.stringify(detail));localStorage.setItem('mhModelVersion','6');}
let capital={...capitalDefaults,...JSON.parse(localStorage.getItem('mhCapital')||'{}')};
let ventures=JSON.parse(JSON.stringify(ventureDefaults));
try{const stored=JSON.parse(localStorage.getItem('mhVentures')||'{}');Object.keys(ventures).forEach(k=>Object.assign(ventures[k],stored[k]||{}));}catch(e){}

const money=n=>`${n<0?'-$':'$'}${Math.abs(Math.round(n||0)).toLocaleString()}`;
const compactMoney=n=>{const a=Math.abs(n||0);const sign=n<0?'−':'';if(a>=1e9)return `${sign}$${(a/1e9).toFixed(a>=1e10?1:2)}B`;if(a>=1e6)return `${sign}$${(a/1e6).toFixed(a>=1e7?1:2)}M`;if(a>=1e3)return `${sign}$${(a/1e3).toFixed(0)}K`;return `${sign}$${Math.round(a)}`};
const pct=n=>`${Number(n||0).toFixed(1)}%`;const num=n=>Math.round(n||0).toLocaleString();
const monthName=x=>`${new Date(x.y,x.m).toLocaleString('en',{month:'short'})} ${x.y}`;

function initTabs(){document.querySelectorAll('.app-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.app-tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-page').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.querySelector(`#tab-${btn.dataset.tab}`).classList.add('active');window.scrollTo({top:360,behavior:'smooth'});});}

function initInputs(){
  const root=document.querySelector('#inputGroups');root.innerHTML='';
  detailGroups.forEach(group=>{const section=document.createElement('div');section.className=`input-group${group.advanced?' advanced-group':''}`;section.innerHTML=`<div class="input-group-head"><div><h3>${group.title}</h3><span>${group.subtitle}</span></div></div><div class="grid"></div>`;const grid=section.querySelector('.grid');group.keys.forEach(k=>{const d=document.createElement('div');d.className='input-card';d.innerHTML=`<label>${labels[k]}</label><input type="number" step="0.01" data-detail="${k}" value="${detail[k]}">`;grid.appendChild(d);});root.appendChild(section);});
  root.oninput=e=>{if(!e.target.dataset.detail)return;detail[e.target.dataset.detail]=+e.target.value;localStorage.setItem('mhDetail',JSON.stringify(detail));renderAll();};
  const capitalLabels={startingBusinessCash:'Starting business cash ($)',ownerDistributionPct:'Owner distribution of positive cash (%)',personalTaxReservePct:'Personal tax reserve (%)',annualPersonalSpend:'Annual personal spending ($)',acquisitionReservePct:'Retained cash tagged for acquisitions (%)'};
  const capRoot=document.querySelector('#capitalInputs');capRoot.innerHTML='';Object.keys(capitalDefaults).forEach(k=>{const d=document.createElement('div');d.className='input-card';d.innerHTML=`<label>${capitalLabels[k]}</label><input type="number" step="0.01" data-capital="${k}" value="${capital[k]}">`;capRoot.appendChild(d);});capRoot.oninput=e=>{if(!e.target.dataset.capital)return;capital[e.target.dataset.capital]=+e.target.value;localStorage.setItem('mhCapital',JSON.stringify(capital));renderAll();};
  let advanced=false;document.querySelector('#showAll').onclick=e=>{advanced=!advanced;document.body.classList.toggle('show-advanced',advanced);e.target.textContent=advanced?'Hide advanced settings':'Show all settings';};
}

const detailYearPlans={
  2027:{startMonth:3,detailers:[2,8,14,20,26,32,38,44,50],offices:[0,1,1,1,1,1,1,1,1]},
  2028:{startMonth:0,detailers:[50,54,58,62,66,70,75,80,85,90,95,100],offices:[1,1,1,2,2,2,2,3,3,3,3,4]},
  2029:{startMonth:0,detailers:[100,105,109,114,118,123,127,132,136,141,145,150],offices:[4,4,4,4,5,5,5,5,6,6,6,6]},
  2030:{startMonth:0,detailers:[150,155,159,164,168,173,177,182,186,191,195,200],offices:[6,6,6,7,7,7,7,8,8,8,8,8]}
};
function officeRent(offices){if(offices<=1)return offices*detail.officeSmall;if(offices===2)return offices*detail.officeMedium;return offices*detail.officeLarge;}
function addCohort(arr,count,monthIndex){if(count>0)arr.push({count,monthIndex});}
function cohortHourlyPayroll(cohorts,monthIndex,startPay,raiseAmt,raiseMonths){const monthlyHours=detail.hoursWeek*detail.weeksYear/12;return cohorts.reduce((sum,c)=>{const tenure=Math.max(0,monthIndex-c.monthIndex);const raises=raiseMonths>0?Math.floor(tenure/raiseMonths):0;return sum+c.count*(startPay+raises*raiseAmt)*monthlyHours;},0);}
function cohortD2DPayroll(cohorts,monthIndex,revenuePerRep){const baseMonthly=detail.d2dBase*detail.weeksYear/12;return cohorts.reduce((sum,c)=>{const tenure=Math.max(0,monthIndex-c.monthIndex);const eligible=detail.salesDay>=detail.d2dRaiseSalesThreshold;const steps=eligible&&detail.d2dRaiseMonths>0?Math.floor(tenure/detail.d2dRaiseMonths):0;const commission=Math.min(detail.d2dCap,detail.d2dCommission+steps*detail.d2dRaise);return sum+c.count*(baseMonthly+revenuePerRep*commission/100);},0);}
function avgD2DCommission(cohorts,monthIndex){const total=cohorts.reduce((a,c)=>a+c.count,0);if(!total)return 0;return cohorts.reduce((sum,c)=>{const tenure=Math.max(0,monthIndex-c.monthIndex);const steps=detail.salesDay>=detail.d2dRaiseSalesThreshold&&detail.d2dRaiseMonths>0?Math.floor(tenure/detail.d2dRaiseMonths):0;return sum+c.count*Math.min(detail.d2dCap,detail.d2dCommission+steps*detail.d2dRaise);},0)/total;}

function buildDetailModel(){
  const months=[];
  Object.entries(detailYearPlans).forEach(([y,p])=>p.detailers.forEach((d,i)=>months.push({y:+y,m:p.startMonth+i,detailers:d,offices:p.offices[i]})));
  // Continue North Splash month-by-month through 2047 so hire-date raises keep applying exactly.
  let priorEOY=200,priorOffices=8;
  for(let y=2031;y<=2047;y++){
    const targetEOY=Math.round(priorEOY*(1+detail.post2030DetailerGrowth/100));
    for(let m=0;m<12;m++){
      const det=Math.round(priorEOY+(targetEOY-priorEOY)*(m+1)/12);
      const off=Math.max(priorOffices,Math.ceil(det/Math.max(1,detail.post2030OfficeEveryDetailers)));
      months.push({y,m,detailers:det,offices:off});
    }
    priorEOY=targetEOY;priorOffices=Math.max(priorOffices,Math.ceil(targetEOY/Math.max(1,detail.post2030OfficeEveryDetailers)));
  }
  const totals={},rowsByYear={},endState={};for(let y=2027;y<=2047;y++){totals[y]={revenue:0,opProfit:0,capex:0,netCash:0,employees:0};rowsByYear[y]=[];}
  let prev={det:0,d2d:0,mgr:0,vans:0,off:0,admin:0,recruiter:0};const cohorts={det:[],d2d:[],mgr:[],admin:[],recruiter:[]};
  months.forEach((x,i)=>{
    const det=x.detailers,d2d=Math.ceil(det/2),vans=Math.ceil(det/2),mgr=Math.floor(vans/5),off=x.offices,admin=off,recruiter=(x.y===2027&&x.m===3)||off===0?0:Math.max(1,Math.ceil(off*detail.recruitersPerOffice));
    const newDet=Math.max(0,det-prev.det),newD=Math.max(0,d2d-prev.d2d),newMgr=Math.max(0,mgr-prev.mgr),newAdmin=Math.max(0,admin-prev.admin),newRecruiter=Math.max(0,recruiter-prev.recruiter),newV=Math.max(0,vans-prev.vans),newOff=Math.max(0,off-prev.off);
    addCohort(cohorts.det,newDet,i);addCohort(cohorts.d2d,newD,i);addCohort(cohorts.mgr,newMgr,i);addCohort(cohorts.admin,newAdmin,i);addCohort(cohorts.recruiter,newRecruiter,i);
    const revenuePerRep=detail.salesDay*detail.daysWeek*detail.ticket*detail.weeksYear/12*(detail.completionRate/100),rev=d2d*revenuePerRep;
    const detPayroll=cohortHourlyPayroll(cohorts.det,i,detail.detailerPay,detail.detailerRaise,detail.detailerRaiseMonths),mgrPayroll=cohortHourlyPayroll(cohorts.mgr,i,detail.managerPay,detail.managerRaise,detail.managerRaiseMonths),adminPayroll=cohortHourlyPayroll(cohorts.admin,i,detail.adminPay,detail.adminRaise,detail.adminRaiseMonths),recruiterPayroll=cohortHourlyPayroll(cohorts.recruiter,i,detail.recruiterPay,0,12),d2dPayroll=cohortD2DPayroll(cohorts.d2d,i,revenuePerRep),wages=detPayroll+mgrPayroll+adminPayroll+recruiterPayroll+d2dPayroll;
    const payrollTaxes=wages*detail.payrollTax/100,workersComp=(detPayroll+mgrPayroll+adminPayroll+recruiterPayroll)*detail.workersComp/100,processing=rev*detail.paymentProcessing/100,recurring=vans*(detail.vanMonthly+detail.hotspot)+d2d*detail.ipadService+officeRent(off)+detail.otherOverhead,recruiting=(newDet+newD+newMgr+newAdmin+newRecruiter)*detail.recruitCost;
    const opProfit=rev-(wages+payrollTaxes+workersComp+processing+recurring+recruiting),capex=newV*(detail.vanPurchase+detail.vanSetup)+newD*detail.ipadPurchase+newOff*detail.officeSetup,netCash=opProfit-capex,avgComm=avgD2DCommission(cohorts.d2d,i),employees=det+d2d+mgr+admin+recruiter;
    totals[x.y].employees=employees;totals[x.y].revenue+=rev;totals[x.y].opProfit+=opProfit;totals[x.y].capex+=capex;totals[x.y].netCash+=netCash;
    rowsByYear[x.y].push({label:monthName(x),det,d2d,vans,mgr,off,rev,avgComm,opProfit,netCash});endState[x.y]={det,d2d,vans,mgr,off,admin,recruiter,employees,avgComm};prev={det,d2d,mgr,vans,off,admin,recruiter};
  });
  return {totals,rowsByYear,endState};
}
function renderFounder(){const sold=detail.salesDay*detail.founderD2DDays*detail.founderWeeks,capacity=detail.founderDetailsDay*detail.founderDetailDays*detail.founderWeeks,completed=Math.min(sold,capacity),backlog=Math.max(0,sold-completed),revenue=completed*detail.ticket*(detail.completionRate/100),hours=detail.founderHoursDay*detail.founderDetailDays*detail.founderWeeks,payroll=hours*detail.founderPartnerPay,tax=payroll*detail.payrollTax/100,wc=payroll*detail.workersComp/100,processing=revenue*detail.paymentProcessing/100,phaseMonths=detail.founderWeeks/(detail.weeksYear/12),recurring=(detail.vanMonthly+detail.hotspot+detail.ipadService)*phaseMonths,profit=revenue-payroll-tax-wc-processing-recurring;[['fpSold',num(sold)],['fpCompleted',num(completed)],['fpBacklog',num(backlog)],['fpRevenue',money(revenue)],['fpPayroll',money(payroll)]].forEach(([id,v])=>document.querySelector('#'+id).textContent=v);const p=document.querySelector('#fpProfit');p.textContent=money(profit);p.className=profit>=0?'positive':'negative';}

function venturePlan(v,endYear=2047){
  const out={};
  let locations=0, prevRevenue=0, expansionReserve=0;
  for(let y=v.startYear;y<=endYear;y++){
    const age=y-v.startYear;
    if(v.isIsland){
      const expansion=y===2047?(v.island2047Equity||0):0;
      const capex=(age===0?v.startupEquity:0)+expansion;
      out[y]={revenue:0,opProfit:0,capex,netCash:-capex,employees:y<2047?v.employees:Math.max(v.employees,120),locations:1,cities:1,states:1,newLocations:age===0?1:0,marketPath:v.marketPath};
      continue;
    }
    if(age===0){
      locations=1;
      const revenue=v.firstRevenue;
      const opProfit=revenue*v.margin/100;
      const capex=v.startupEquity;
      expansionReserve=Math.max(0,opProfit)*(v.reinvestPct||0)/100;
      out[y]={revenue,opProfit,capex,netCash:opProfit-capex,employees:Math.max(v.employees,Math.round(locations*v.employeesPerLocation)),locations,cities:1,states:1,newLocations:1,marketPath:v.marketPath,expansionReserve};
      prevRevenue=revenue;
      continue;
    }
    const prev=out[y-1];
    // Expansion is funded from a controlled share of prior operating profit, then capped so branches never grow recklessly in one year.
    expansionReserve+=Math.max(0,prev.opProfit)*(v.reinvestPct||0)/100;
    const affordable=Math.floor(expansionReserve/Math.max(1,v.expansionEquity));
    const growthCap=Math.max(1,Math.ceil(prev.locations*(v.maxLocationGrowthPct||0)/100));
    const remaining=Math.max(0,(v.maxLocations||9999)-prev.locations);
    const newLocations=Math.min(affordable,growthCap,remaining);
    locations=prev.locations+newLocations;
    const sameStoreFactor=1+(v.sameStoreGrowth||0)/100;
    const establishedRevenue=prev.revenue*sameStoreFactor;
    // New branches ramp at 70% of first-year mature location revenue in their opening year.
    const newLocationRevenue=newLocations*v.firstRevenue*0.70;
    const revenue=establishedRevenue+newLocationRevenue;
    const scaleMarginBonus=Math.min(4,Math.log2(Math.max(1,locations))*0.45);
    const effectiveMargin=Math.min(v.margin+scaleMarginBonus,v.margin+4);
    const opProfit=revenue*effectiveMargin/100;
    const capex=newLocations*v.expansionEquity;
    expansionReserve=Math.max(0,expansionReserve-capex);
    // A portion of current-year profit is earmarked for the next expansion cycle; capex is still shown separately as cash invested.
    const netCash=opProfit-capex;
    const employees=Math.max(v.employees,Math.round(locations*v.employeesPerLocation*Math.pow(revenue/Math.max(1,locations*v.firstRevenue),0.35)));
    const cities=Math.max(1,Math.ceil(locations/Math.max(1,v.locationsPerCity||1)));
    const states=Math.max(1,Math.ceil(locations/Math.max(1,v.locationsPerState||5)));
    out[y]={revenue,opProfit,capex,netCash,employees,locations,cities,states,newLocations,marketPath:v.marketPath,effectiveMargin,expansionReserve};
    prevRevenue=revenue;
  }
  return out;
}
function ventureYear(v,y){if(y<v.startYear)return null;return venturePlan(v,y)[y]||null;}

function buildPortfolio(detailModel){const years={};for(let y=2027;y<=2047;y++){const d=detailModel.totals[y];const detLoc=detailModel.endState[y].off;const companies=[{id:'detailing',name:'North Splash Auto Luxe',division:'Service',...d,locations:detLoc,cities:Math.max(1,Math.ceil(detLoc/1.4)),states:Math.max(1,Math.ceil(detLoc/10)),marketPath:'Raleigh → Triangle → North Carolina → Southeast → East Coast → high-opportunity U.S. metros'}];Object.entries(ventures).forEach(([id,v])=>{const a=ventureYear(v,y);if(a)companies.push({id,name:v.name,division:v.division,...a});});const total=companies.reduce((a,c)=>({revenue:a.revenue+c.revenue,opProfit:a.opProfit+c.opProfit,capex:a.capex+c.capex,netCash:a.netCash+c.netCash,employees:a.employees+c.employees}),{revenue:0,opProfit:0,capex:0,netCash:0,employees:0});years[y]={companies,total};}return years;}

const roadmap={
  2027:{goal:'Scale North Splash to 50 detailers',before:'Working founder phase validated; operating cash reserve; hiring, scheduling and quality-control systems.',start:'Move from founder phase into crew-based operations. Add vans only with booked demand. Open the first small office in May.',milestone:'50 detailers / 25 vans target with profitable core crews and management handling daily work.'},
  2028:{goal:'Regional detailing + launch clothing',before:'North Splash has leaders, cash reserves and repeatable recruiting.',start:'Expand North Splash offices and launch the clothing brand online with small inventory tests.',milestone:'Detailing succeeds outside the first territory and clothing shows repeat profitable demand.'},
  2029:{goal:'Launch commercial cleaning',before:'Central admin, recruiting and finance can support another service company.',start:'Build recurring B2B contracts in medical, office, retail and warehouse accounts.',milestone:'Cleaning contracts cover crews and supervision with predictable recurring revenue.'},
  2030:{goal:'Launch pressure washing',before:'Existing residential/commercial customer lists and sales team are active.',start:'Cross-sell detailing, cleaning, HOA and property-management accounts.',milestone:'Four operating companies are profitable with executive oversight.'},
  2031:{goal:'Multi-city operating system',before:'Regional managers, SOPs, centralized accounting/HR and quality audits.',start:'Deepen the strongest markets instead of adding cities only for appearance.',milestone:'Multiple markets stay profitable without owner involvement in daily operations.'},
  2032:{goal:'Acquire entertainment + commercial property',before:'Strong cash flow, lender relationships, acquisition reserve, CPA and commercial attorney.',start:'Buy a positive-cash-flow bowling/entertainment business and first operating real estate.',milestone:'Entertainment and property both produce positive cash flow after debt service and reserves.'},
  2033:{goal:'Launch construction management',before:'Real projects to manage, experienced project executives, insurance and legal structure.',start:'Manage budgets, schedules, procurement and subcontractor coordination.',milestone:'Projects finish on schedule/budget and team can support first apartment development.'},
  2034:{goal:'First apartment development',before:'Land pipeline, architect/engineers, investors, construction lender and development team.',start:'Secure site, entitlements, financing and build the first apartment community.',milestone:'First project completes and reaches a stable lease-up trajectory.'},
  2035:{goal:'Property management + repeat development',before:'First development operating and internal systems ready for resident/property operations.',start:'Manage owned assets internally and selectively add third-party contracts.',milestone:'Property operations are dependable and second development pipeline is funded.'},
  2036:{goal:'Apartment ownership + general contracting',before:'Development track record, project controls, experienced licensed leadership and financing.',start:'Hold stabilized apartments for recurring income while growing internal GC capability.',milestone:'Recurring real-estate cash flow plus repeatable construction execution.'},
  2037:{goal:'Scale real estate and construction',before:'Multiple projects with clear KPIs, risk controls and regional leaders.',start:'Run multiple developments without overloading a single management team.',milestone:'Several stabilized assets and projects delivered consistently.'},
  2038:{goal:'Enter hospitality',before:'Real-estate operations, property management and strong executive leadership.',start:'Acquire/build a boutique resort with restaurant, events and guest-experience systems.',milestone:'Hospitality operates profitably for a full cycle with a professional GM team.'},
  2039:{goal:'Investment company + site development',before:'Audited financials, investor relationships, compliance counsel and construction pipeline.',start:'Structure investor-backed deals and build site-development capacity around owned projects.',milestone:'Outside capital participates successfully and site work is consistently controlled.'},
  2040:{goal:'Luxury apartment communities',before:'Proven large-project team, property management, GC/site development and investor demand.',start:'Develop larger premium multifamily communities using repeatable design/operations.',milestone:'Large projects stabilize while portfolio leverage remains manageable.'},
  2041:{goal:'Multi-state portfolio',before:'Regional leadership and centralized risk, HR, finance and legal systems.',start:'Scale strongest service, construction and asset businesses into selected states.',milestone:'Multiple states remain profitable and quality standards stay consistent.'},
  2042:{goal:'Executive depth',before:'Bench of division presidents/CFO/COO-level leadership.',start:'Reduce founder dependence and formalize capital allocation across divisions.',milestone:'Holding company can operate for extended periods without daily founder intervention.'},
  2043:{goal:'Prepare legacy-scale capital',before:'Large recurring cash flow, institutional reporting and proven investor returns.',start:'Build acquisition reserve and shortlist destination-scale hospitality/development opportunities.',milestone:'Liquidity and financing capacity support island due diligence without risking core businesses.'},
  2044:{goal:'Island research & feasibility',before:'Dedicated legal, environmental, engineering, hospitality and logistics advisors.',start:'Compare islands, access, jurisdiction, utilities, development rights, weather and environmental constraints.',milestone:'Shortlist passes legal, environmental, infrastructure and financial feasibility tests.'},
  2045:{goal:'Form island development operation',before:'Preferred island identified and preliminary feasibility complete.',start:'Finalize master plan, logistics model, marina/dock concepts, workforce housing and infrastructure budget.',milestone:'Development plan and financing structure are credible enough for final negotiations.'},
  2046:{goal:'Secure financing & purchase readiness',before:'Contracts, investor commitments, lender term sheets and detailed due diligence.',start:'Finalize acquisition entity, infrastructure contracts, material-transport plan and operating teams.',milestone:'Purchase can close without unresolved legal, environmental or capital gaps.'},
  2047:{goal:'Acquire island + Phase 1 infrastructure',before:'Purchase capital funded, approvals understood, logistics and emergency plans ready.',start:'Close acquisition; prioritize dock/marina access, power, water, wastewater, roads, communications, worker housing and maintenance.',milestone:'Island is secured and core infrastructure phase is funded before resort expansion begins.'}
};

function renderVentureCards(){const root=document.querySelector('#ventureCards');root.innerHTML=Object.entries(ventures).map(([id,v])=>{const y2047=ventureYear(v,2047);return `<article class="venture-card"><div class="venture-head"><div><span class="kicker">${v.division.toUpperCase()}</span><h3>${v.name}</h3><p>${v.note}</p></div><div class="venture-year">${v.startYear}</div></div><div class="venture-body"><div class="venture-stats"><div class="venture-stat"><span>2047 REVENUE</span><b>${compactMoney(y2047?.revenue||0)}</b></div><div class="venture-stat"><span>2047 PROFIT</span><b class="${(y2047?.opProfit||0)>=0?'positive':'negative'}">${compactMoney(y2047?.opProfit||0)}</b></div><div class="venture-stat"><span>EMPLOYEES</span><b>${num(y2047?.employees||0)}</b></div><div class="venture-stat"><span>2047 LOCATIONS</span><b>${num(y2047?.locations||0)}</b></div><div class="venture-stat"><span>EST. STATES</span><b>${num(y2047?.states||0)}</b></div></div><div class="venture-inputs">${[['startYear','Launch year'],['firstRevenue','Year-1 revenue ($)'],['margin','Base operating margin (%)'],['sameStoreGrowth','Same-location growth (%)'],['employees','Starting employees'],['employeesPerLocation','Employees / location'],['reinvestPct','Profit reinvested into expansion (%)'],['maxLocationGrowthPct','Max branch growth / year (%)'],['maxLocations','2047 location ceiling'],['startupEquity','Launch cash equity ($)'],['expansionEquity','Expansion cash/location ($)'],['totalProjectCost','Total project/value ($)'],['locationsPerState','Locations / state estimate']].map(([k,l])=>`<div class="venture-input"><label>${l}</label><input type="number" step="0.01" data-venture="${id}" data-field="${k}" value="${v[k]}"></div>`).join('')}${v.isIsland?`<div class="venture-input"><label>2047 purchase equity ($)</label><input type="number" data-venture="${id}" data-field="island2047Equity" value="${v.island2047Equity}"></div>`:''}</div><p class="venture-note"><b>Expansion path:</b> ${v.marketPath||'Build density first, then expand regionally.'}</p><p class="venture-note">Expansion is profit-driven: a controlled share of prior-year operating profit funds new locations, with an annual growth cap. Cash equity is the M Holdings contribution; total project value can be larger through financing/investors.</p></div></article>`;}).join('');root.onchange=e=>{const id=e.target.dataset.venture,field=e.target.dataset.field;if(!id||!field)return;ventures[id][field]=+e.target.value;localStorage.setItem('mhVentures',JSON.stringify(ventures));renderAll(true);};}

function renderDetail(detailModel){renderFounder();document.querySelector('#heroTicket').textContent=money(detail.ticket);const summaryYears=[2027,2028,2029,2030];document.querySelector('#detailYearSummary').innerHTML=summaryYears.map(y=>{const t=detailModel.totals[y],e=detailModel.endState[y];return `<div class="year-summary-card"><span>${y} REVENUE</span><strong>${compactMoney(t.revenue)}</strong><b class="year-profit ${t.opProfit>=0?'positive':'negative'}">${compactMoney(t.opProfit)} profit</b><small>${pct(t.opProfit/t.revenue*100)} margin · ${e.det} detailers · ${e.off} offices</small></div>`;}).join('');
  const open=new Set(JSON.parse(sessionStorage.getItem('mhDetailOpen')||'[2027]'));document.querySelector('#detailYears').innerHTML=[2027,2028,2029,2030].map(y=>{const t=detailModel.totals[y],e=detailModel.endState[y],rows=detailModel.rowsByYear[y],isOpen=open.has(y);return `<div class="year-group ${isOpen?'open':''}" data-detail-year="${y}"><button class="year-toggle" type="button"><span class="year-label">${y}</span><span class="year-meta"><span>Revenue <b>${compactMoney(t.revenue)}</b></span><span>Profit <b class="${t.opProfit>=0?'positive':'negative'}">${compactMoney(t.opProfit)}</b></span><span>Cash <b>${compactMoney(t.netCash)}</b></span><span>EOY <b>${e.det} detailers · ${e.d2d} D2D · ${e.off} offices</b></span></span><span class="chevron">⌄</span></button><div class="year-months"><div class="tablewrap"><table><thead><tr><th>Month</th><th>Detailers</th><th>D2D</th><th>Vans</th><th>Managers</th><th>Offices</th><th>Revenue</th><th>Avg D2D %</th><th>Operating Profit</th><th>Net Cash Flow</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.label}</td><td>${r.det}</td><td>${r.d2d}</td><td>${r.vans}</td><td>${r.mgr}</td><td>${r.off}</td><td>${money(r.rev)}</td><td>${pct(r.avgComm)}</td><td class="${r.opProfit>=0?'positive':'negative'}">${money(r.opProfit)}</td><td class="${r.netCash>=0?'positive':'negative'}">${money(r.netCash)}</td></tr>`).join('')}</tbody></table></div></div></div>`;}).join('');document.querySelectorAll('[data-detail-year] .year-toggle').forEach(btn=>btn.onclick=()=>{const g=btn.closest('.year-group');g.classList.toggle('open');sessionStorage.setItem('mhDetailOpen',JSON.stringify([...document.querySelectorAll('[data-detail-year].open')].map(x=>+x.dataset.detailYear)));});
  const unitRev=detail.salesDay*detail.daysWeek*detail.ticket*detail.weeksYear/12*(detail.completionRate/100),detStart=2*detail.detailerPay*detail.hoursWeek*detail.weeksYear/12,d2dStart=detail.d2dBase*detail.weeksYear/12+unitRev*detail.d2dCommission/100,d2dCap=detail.d2dBase*detail.weeksYear/12+unitRev*detail.d2dCap/100;const units=[['1 D2D monthly revenue',unitRev],['2 detailers starting payroll',detStart],['1 D2D starting pay',d2dStart],['1 D2D pay at commission cap',d2dCap],['1 van monthly operations',detail.vanMonthly+detail.hotspot],['1 manager starting payroll',detail.managerPay*detail.hoursWeek*detail.weeksYear/12],['1 admin starting payroll',detail.adminPay*detail.hoursWeek*detail.weeksYear/12],['New van + setup',detail.vanPurchase+detail.vanSetup],['Recruiting per hire',detail.recruitCost]];document.querySelector('#unitCosts').innerHTML=units.map(a=>`<div class="unit"><span>${a[0]}</span><b>${money(a[1])}</b></div>`).join('');
}

function renderPortfolio(portfolio,detailModel){const active2047=portfolio[2047].companies.length,tot2047=portfolio[2047].total;document.querySelector('#heroVentures').textContent=active2047;const cumulativeRevenue=Object.values(portfolio).reduce((a,y)=>a+y.total.revenue,0),cumulativeProfit=Object.values(portfolio).reduce((a,y)=>a+y.total.opProfit,0);document.querySelector('#portfolioKpis').innerHTML=[['2047 revenue',compactMoney(tot2047.revenue),'Annual portfolio revenue'],['2047 operating profit',compactMoney(tot2047.opProfit),pct(tot2047.opProfit/tot2047.revenue*100)+' margin'],['2047 employees',num(tot2047.employees),'Across active companies'],['2027–47 revenue',compactMoney(cumulativeRevenue),'Scenario cumulative'],['2027–47 profit',compactMoney(cumulativeProfit),'Before expansion cash']].map(([a,b,c])=>`<div class="kpi"><span>${a.toUpperCase()}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
  const open=new Set(JSON.parse(sessionStorage.getItem('mhPortfolioOpen')||'[2027,2030,2040,2047]'));document.querySelector('#portfolioYears').innerHTML=Object.entries(portfolio).map(([y,data])=>{const yr=+y,isOpen=open.has(yr),launches=data.companies.filter(c=>c.id!=='detailing'&&ventures[c.id]?.startYear===yr).map(c=>c.name),t=data.total;return `<div class="year-group ${isOpen?'open':''}" data-port-year="${yr}"><button class="year-toggle" type="button"><span class="year-label">${yr}</span><span class="year-meta"><span>Revenue <b>${compactMoney(t.revenue)}</b></span><span>Profit <b class="${t.opProfit>=0?'positive':'negative'}">${compactMoney(t.opProfit)}</b></span><span>Net cash <b class="${t.netCash>=0?'positive':'negative'}">${compactMoney(t.netCash)}</b></span><span>Employees <b>${num(t.employees)}</b></span>${launches.length?`<span>Launch <b>${launches.join(' · ')}</b></span>`:''}</span><span class="chevron">⌄</span></button><div class="year-months"><div class="tablewrap"><table><thead><tr><th>Company</th><th>Division</th><th>Revenue</th><th>Operating Profit</th><th>Expansion Cash</th><th>Net Cash Flow</th><th>Employees</th><th>Locations/Assets</th><th>Cities</th><th>States</th></tr></thead><tbody>${data.companies.map(c=>`<tr><td>${c.name}</td><td>${c.division}</td><td>${money(c.revenue)}</td><td class="${c.opProfit>=0?'positive':'negative'}">${money(c.opProfit)}</td><td>${money(c.capex)}</td><td class="${c.netCash>=0?'positive':'negative'}">${money(c.netCash)}</td><td>${num(c.employees)}</td><td>${num(c.locations||0)}</td><td>${num(c.cities||Math.ceil((c.locations||1)/2))}</td><td>${num(c.states||1)}</td></tr>`).join('')}</tbody></table></div></div></div>`;}).join('');document.querySelectorAll('[data-port-year] .year-toggle').forEach(btn=>btn.onclick=()=>{const g=btn.closest('.year-group');g.classList.toggle('open');sessionStorage.setItem('mhPortfolioOpen',JSON.stringify([...document.querySelectorAll('[data-port-year].open')].map(x=>+x.dataset.portYear)));});
  const divisions={Service:['North Splash Auto Luxe','Commercial Cleaning','Pressure Washing'],Retail:['Clothing Brand'],Entertainment:['Bowling & Entertainment'],'Real Estate':['Commercial Real Estate','Apartment Development','Property Management','Apartment Ownership'],Construction:['Construction Management','General Contracting','Site Development'],Hospitality:['Hospitality & Resorts'],Capital:['Investment Company'],Island:['Island Development']};document.querySelector('#divisionGrid').innerHTML=Object.entries(divisions).map(([d,names])=>`<div class="division-card"><h3>${d}</h3><p>${d==='Service'?'Cash-flow engines and customer acquisition.':d==='Real Estate'?'Long-term assets, rent and development equity.':d==='Construction'?'Build and project execution capabilities.':d==='Hospitality'?'Destination operations before the island phase.':d==='Capital'?'Investor relationships and larger deal financing.':d==='Island'?'2045–47 feasibility, financing, acquisition and infrastructure.':'Brand and diversified operating income.'}</p><div class="mini-tags">${names.map(n=>`<span class="mini-tag">${n}</span>`).join('')}</div></div>`).join('');
}

function renderMarkets(portfolio){
  const y=2047,data=portfolio[y];
  const totalLocations=data.companies.reduce((a,c)=>a+(c.locations||0),0);
  const maxStates=Math.max(...data.companies.map(c=>c.states||1));
  const expansionCash=Object.values(portfolio).reduce((a,yr)=>a+yr.total.capex,0);
  document.querySelector('#marketKpis').innerHTML=[['2047 locations/assets',num(totalLocations),'Across the full portfolio'],['Largest state footprint',num(maxStates),'Estimated states for widest division'],['2047 active companies',num(data.companies.length),'Operating ventures'],['2027–47 expansion cash',compactMoney(expansionCash),'Startup + growth equity'],['North Splash offices',num(data.companies.find(c=>c.id==='detailing')?.locations||0),'Profit-supported service hubs']].map(([a,b,c])=>`<div class="kpi"><span>${a.toUpperCase()}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
  const years=[2028,2030,2032,2035,2040,2047];
  document.querySelector('#marketCards').innerHTML=data.companies.map(c=>{
    const v=c.id==='detailing'?null:ventures[c.id];
    const path=c.marketPath||v?.marketPath||'Build density first, then expand regionally.';
    const milestones=years.map(yr=>{const co=portfolio[yr]?.companies.find(x=>x.id===c.id);return co?`<div class="market-year"><span>${yr}</span><b>${num(co.locations||0)} loc.</b><small>${num(co.cities||1)} cities · ${num(co.states||1)} states</small></div>`:''}).join('');
    return `<article class="market-card"><div class="market-card-head"><div><span class="kicker">${c.division.toUpperCase()}</span><h3>${c.name}</h3></div><b>${num(c.locations||0)} <small>2047 locations/assets</small></b></div><p>${path}</p><div class="market-years">${milestones}</div></article>`;
  }).join('');
}

function renderRoadmap(portfolio){const open=new Set(JSON.parse(sessionStorage.getItem('mhRoadmapOpen')||'[2027,2034,2047]'));document.querySelector('#roadmapYears').innerHTML=Object.entries(roadmap).map(([y,r])=>{const yr=+y,isOpen=open.has(yr),launches=portfolio[yr].companies.filter(c=>c.id!=='detailing'&&ventures[c.id]?.startYear===yr).map(c=>c.name);return `<div class="year-group ${isOpen?'open':''}" data-road-year="${yr}"><button class="year-toggle" type="button"><span class="year-label">${yr}</span><span class="year-meta"><span>Goal <b>${r.goal}</b></span><span>Revenue <b>${compactMoney(portfolio[yr].total.revenue)}</b></span><span>Profit <b>${compactMoney(portfolio[yr].total.opProfit)}</b></span></span><span class="chevron">⌄</span></button><div class="year-months"><div class="roadmap-content">${launches.length?`<ul class="launch-list">${launches.map(x=>`<li>Launch: ${x}</li>`).join('')}</ul>`:''}<div class="roadmap-grid"><div class="roadmap-box"><span>BEFORE YOU START</span><p>${r.before}</p></div><div class="roadmap-box"><span>HOW TO START</span><p>${r.start}</p></div><div class="roadmap-box"><span>MILESTONE TO MOVE ON</span><p>${r.milestone}</p></div></div></div></div></div>`;}).join('');document.querySelectorAll('[data-road-year] .year-toggle').forEach(btn=>btn.onclick=()=>{const g=btn.closest('.year-group');g.classList.toggle('open');sessionStorage.setItem('mhRoadmapOpen',JSON.stringify([...document.querySelectorAll('[data-road-year].open')].map(x=>+x.dataset.roadYear)));});}

function renderCapital(portfolio){let businessCash=capital.startingBusinessCash,personalSavings=0;const rows=[];let totalDistributions=0;for(let y=2027;y<=2047;y++){const t=portfolio[y].total;const distributable=Math.max(0,t.netCash),distribution=distributable*capital.ownerDistributionPct/100,retained=t.netCash-distribution;businessCash+=retained;const afterTaxDistribution=distribution*(1-capital.personalTaxReservePct/100),personalDelta=afterTaxDistribution-capital.annualPersonalSpend;personalSavings+=personalDelta;totalDistributions+=distribution;const acquisitionFund=Math.max(0,businessCash)*capital.acquisitionReservePct/100;rows.push(`<tr><td>${y}</td><td>${money(t.revenue)}</td><td class="${t.opProfit>=0?'positive':'negative'}">${money(t.opProfit)}</td><td>${money(t.capex)}</td><td class="${t.netCash>=0?'positive':'negative'}">${money(t.netCash)}</td><td>${money(businessCash)}</td><td>${money(distribution)}</td><td class="${personalSavings>=0?'positive':'negative'}">${money(personalSavings)}</td><td>${money(acquisitionFund)}</td></tr>`);}document.querySelector('#capitalRows').innerHTML=rows.join('');document.querySelector('#capitalKpis').innerHTML=[['2047 retained business cash',compactMoney(businessCash),'After expansion + owner distributions'],['2047 personal savings',compactMoney(personalSavings),'After tax reserve + spending assumption'],['Total owner distributions',compactMoney(totalDistributions),'2027–2047'],['Acquisition fund target',compactMoney(Math.max(0,businessCash)*capital.acquisitionReservePct/100),`${capital.acquisitionReservePct}% of retained cash`],['2047 island cash equity',compactMoney(ventures.island.island2047Equity),'Editable in Businesses']].map(([a,b,c])=>`<div class="kpi"><span>${a.toUpperCase()}</span><strong>${b}</strong><small>${c}</small></div>`).join('');}

function renderAll(refreshVentures=true){const detailModel=buildDetailModel(),portfolio=buildPortfolio(detailModel);renderDetail(detailModel);if(refreshVentures)renderVentureCards();renderPortfolio(portfolio,detailModel);renderMarkets(portfolio);renderRoadmap(portfolio);renderCapital(portfolio);}

function exportCSV(){const d=buildDetailModel(),p=buildPortfolio(d),headers=['Year','Company','Division','Revenue','Operating Profit','Expansion Cash','Net Cash Flow','Employees','Locations','Cities','States'];const lines=[headers.join(',')];Object.entries(p).forEach(([y,data])=>data.companies.forEach(c=>lines.push([y,c.name,c.division,Math.round(c.revenue),Math.round(c.opProfit),Math.round(c.capex),Math.round(c.netCash),c.employees,c.locations||0,c.cities||0,c.states||0].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))));const blob=new Blob([lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='m-holdings-2027-2047.csv';a.click();URL.revokeObjectURL(a.href);}

document.querySelector('#export').onclick=exportCSV;document.querySelector('#reset').onclick=()=>{if(confirm('Reset the entire M Holdings scenario back to the built-in defaults?')){['mhDetail','mhCapital','mhVentures'].forEach(k=>localStorage.removeItem(k));location.reload();}};
initTabs();initInputs();renderAll();
