const defaults={ticket:200,salesDay:3.5,daysWeek:5,detailerPay:17,managerPay:22,adminPay:24,d2dBase:300,d2dCommission:10,d2dRaise:2,d2dCap:22,vanPurchase:3000,vanSetup:2000,vanMonthly:1200,ipadPurchase:500,ipadService:40,hotspot:50,payrollTax:7.65,recruitCost:150,officeSmall:1000,officeLarge:3500};
const labels={ticket:'Average detail ($)',salesDay:'D2D sales / day',daysWeek:'Selling days / week',detailerPay:'Detailer starting $/hr',managerPay:'Manager starting $/hr',adminPay:'Admin $/hr',d2dBase:'D2D base $/week',d2dCommission:'D2D starting commission %',d2dRaise:'D2D raise every 2 months %',d2dCap:'D2D commission cap %',vanPurchase:'Average van purchase ($)',vanSetup:'Van equipment/setup ($)',vanMonthly:'Van monthly operating ($)',ipadPurchase:'iPad purchase ($)',ipadService:'iPad service / month ($)',hotspot:'Hotspot / van / month ($)',payrollTax:'Employer payroll tax %',recruitCost:'Recruiting / new hire ($)',officeSmall:'Small office / month ($)',officeLarge:'Larger office / month ($)'};
let s={...defaults,...JSON.parse(localStorage.getItem('nsPlanner')||'{}')};const inputBox=document.querySelector('#inputs');
Object.keys(defaults).forEach(k=>{let d=document.createElement('div');d.className='field';d.innerHTML=`<label>${labels[k]}</label><input type="number" step="0.01" data-k="${k}" value="${s[k]}">`;inputBox.appendChild(d)});
inputBox.addEventListener('input',e=>{if(!e.target.dataset.k)return;s[e.target.dataset.k]=+e.target.value;localStorage.setItem('nsPlanner',JSON.stringify(s));render()});document.querySelector('#reset').onclick=()=>{localStorage.removeItem('nsPlanner');location.reload()};
const months=[];for(let y=2027;y<=2028;y++){let start=y===2027?3:0;for(let m=start;m<12;m++)months.push({y,m})}const targetDetailers=[2,8,14,20,26,32,38,44,50,50,54,58,62,66,70,75,80,85,90,95,100];
const money=n=>'$'+Math.round(n).toLocaleString();function monthsSinceApr27(i){return i}
function render(){let rows='',tot27R=0,tot27P=0,tot28R=0,tot28P=0,prev={d:0,d2d:0,mgr:0,vans:0,off:0};months.forEach((x,i)=>{let det=targetDetailers[i],d2d=Math.ceil(det/2),vans=Math.ceil(det/2),mgr=Math.max(1,Math.ceil(vans/4)),off=x.y===2027?(i<6?1:i<9?1:1):(i<12?1:i<16?2:i<20?3:4);let admin=off;let weeklyRevenue=d2d*s.salesDay*s.daysWeek*s.ticket,rev=weeklyRevenue*52/12;
let detMonths=monthsSinceApr27(i),detRate=s.detailerPay+Math.floor(detMonths/6),mgrRate=s.managerPay+Math.floor(detMonths/6);let detPayroll=det*detRate*40*52/12,mgrPayroll=mgr*mgrRate*40*52/12,adminPayroll=admin*s.adminPay*40*52/12;
let avgComm=Math.min(s.d2dCap,s.d2dCommission+Math.floor(detMonths/2)*s.d2dRaise);let d2dPay=d2d*s.d2dBase*52/12+rev*(avgComm/100);let wages=detPayroll+mgrPayroll+adminPayroll+d2dPay,tax=wages*s.payrollTax/100;
let recurring=vans*(s.vanMonthly+s.hotspot)+d2d*s.ipadService+off*(x.y===2028&&off>=3?s.officeLarge:s.officeSmall);let newDet=Math.max(0,det-prev.d),newD=Math.max(0,d2d-prev.d2d),newMgr=Math.max(0,mgr-prev.mgr),newV=Math.max(0,vans-prev.vans),newOff=Math.max(0,off-prev.off);let growth=(newDet+newD+newMgr+newOff)*s.recruitCost+newV*(s.vanPurchase+s.vanSetup)+newD*s.ipadPurchase;let profit=rev-wages-tax-recurring-growth;
if(x.y===2027){tot27R+=rev;tot27P+=profit}else{tot28R+=rev;tot28P+=profit}rows+=`<tr><td>${new Date(x.y,x.m).toLocaleString('en',{month:'short'})} ${x.y}</td><td>${det}</td><td>${d2d}</td><td>${vans}</td><td>${mgr}</td><td>${off}</td><td>${money(rev)}</td><td>${money(profit)}</td></tr>`;prev={d:det,d2d,mgr,vans,off}});document.querySelector('#projection').innerHTML=rows;document.querySelector('#r27').textContent=money(tot27R);document.querySelector('#p27').textContent=money(tot27P);document.querySelector('#r28').textContent=money(tot28R);document.querySelector('#p28').textContent=money(tot28P);document.querySelector('#heroTicket').textContent=money(s.ticket);
let unitRev=s.salesDay*s.daysWeek*s.ticket*52/12,det=2*s.detailerPay*40*52/12,d2d=s.d2dBase*52/12+unitRev*s.d2dCommission/100;let units=[['1 D2D revenue',unitRev],['2 detailers payroll',det],['1 D2D starting pay',d2d],['1 van operations',s.vanMonthly],['1 manager payroll',s.managerPay*40*52/12],['1 admin payroll',s.adminPay*40*52/12],['New van + setup',s.vanPurchase+s.vanSetup],['Recruiting per hire',s.recruitCost]];document.querySelector('#unitCosts').innerHTML=units.map(a=>`<div class="unit"><span>${a[0]}</span><b>${money(a[1])}</b></div>`).join('')}
render();
